### ISSUE TITLE
The system library `com_err` required by crate `afsr` was not found

### ISSUE THREAD

**Issue by pixincreate** [chenxiaolong/afsr#2]
Hey there!

I have got another question. I went through `afsr` README and learnt that it is a personal project and hence the binary needs to be built from scratch. I haven't yet tried building it on my Windows machine. I'm trying to build it on my Mac but ran into issues with it.  

It required me to install `pkg_config` from brew which I did and now it says it cannot find `com_err`:

```

Caused by:
  process didn't exit successfully: `afsr/target/release/build/afsr-91abb1dc3981f0d7/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=COM_ERR_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=COM_ERR_STATIC
  cargo:rerun-if-env-changed=COM_ERR_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at build.rs:33:56:
  called `Result::unwrap()` on an `Err` value:
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags com_err

  The system library `com_err` required by crate `afsr` was not found.
  The file `com_err.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `com_err.pc`.

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

I'm here because I couldn't find much info about this.

I wanted to try `my-avbroot-setup` before I proceed further with my automated build script and started to run into issues while doing so.

**Comment by pixincreate** [comment]
okay, i solved it by doing:

```
brew install e2fsprogs
echo /opt/homebrew/Cellar/e2fsprogs/1.47.1/lib/pkgconfig | pbcopy # e2fsprogs version cannot be checked directly
vi ~/.zsh/.zshenv
# paste from clipboard
:wq!
source ~/.zsh/.zshenv
cargo run --release
```

**Comment by chenxiaolong** [comment]
In the future, I might add an optional flag to compile a bundled version of e2fsprogs so that a system version is not needed. At least homebrew on Mac has it. msys2 on Windows does not.

That would make it much easier to provide precompiled binaries.

**Comment by pixincreate** [comment]
Thanks for this, homebrew on Mac has it, yes, but that does not set up the paths for `.pc` which has to be done manually.

Also, I learnt it the hard way that all modules are required and not optional, LOL.

**Comment by chenxiaolong** [comment]
I started looking into this a bit. Looks like it'll be easier than I thought to compile e2fsprogs as part of afsr's build. Might take me a little bit to finish though. I don't have a Mac or Windows system so I'll have to add CI workflows and test the build process via Github Actions.

> Also, I learnt it the hard way that all modules are required and not optional, LOL.

Sorry :smile: I basically made the script only for my own needs and kind of expected people to fork and modify it.

**Comment by chenxiaolong** [comment]
Ah crap, nevermind. Bundling the library parts of e2fsprogs isn't sufficient. That would result in an afsr executable that can only unpack, but not pack.

I totally forgot afsr depends on the external `mke2fs` executable too. That's not something I can incorporate due to license conflicts.

I'll at least merge a few changes needed to fix compiling on Windows and Linux aarch64, but I won't provide binaries.

**Comment by pixincreate** [comment]
> I don't have a Mac or Windows system so I'll have to add CI workflows and test the build process via Github Actions.

I can help you with that if needed.

I haven't tested this on my Windows machine. But on Mac, you need `pkg-config` and `e2fsprogs` to be installed from `brew`.

> I basically made the script only for my own needs and kind of expected people to fork and modify it

I learnt the moment I read the readme and `unwrap()`, lol. I would want to improve this this weekend.

> Ah crap, nevermind. Bundling the library parts of e2fsprogs isn't sufficient. That would result in an afsr executable that can only unpack, but not pack.

I do not find the need to make it an executable, but rather, making it clearer in readme would suffice?

**Comment by chenxiaolong** [comment]
I keep thinking about this. I really do want to provide precompiled binaries for people to easily use, like with avbroot and custota.

I was originally thinking of relicensing afsr to GPLv2 so that `mke2fs` could maybe be included in afsr as a single executable. That won't work because afsr also depends on Apache2-licensed libraries, which are only compatible with GPLv3.

---

So my thought now is (for the Github Actions workflow that builds the precompiled binaries):

* Compile e2fsprogs as static libraries and static executables.
* Point pkg-config at the local static libraries instead of using the system shared libraries.
* Build afsr.
* Ship both the `afsr` and `mke2fs` executables in the release zip.

The `com_err`, `e2p`, and `ext2fs` libraries will be statically linked into afsr, which is fine because their licenses (MIT and LGPLv2) are compatible with afsr's (GPLv3). `mke2fs`'s license is not compatible, but it'll be a separate executable, not linked to afsr, so that won't be a problem either.

**Comment by pixincreate** [comment]
Damn, I never knew licensing a project would come with this many risks involved. I mean, I have multiple projects that have contradictory licenses and I never cared much about them. I should give it another thought and change them accordingly.  

Coming back to this (afsr), since providing pre-compiled binaries is an issue with licensing, I feel the latter is more than sufficient i.e., putting required files in a zip as separate files.

Again, I do not much experiences with licensing stuff, just typing what's coming to my midn at the moment.

**Comment by pixincreate** [comment]
I'm getting into the same issue on Ubuntu it seems:

https://github.com/pixincreate/PixeneOS/actions/workflows/pathtest.yml

Have been trying to find `com_err.pc`, but that does not seem to help in any way.

I think I should better until #5 is merged?

**Comment by chenxiaolong** [comment]
On Linux, you should never need to set pkg-config paths. I think you might just need to `apt-get install comerr-dev` (https://packages.ubuntu.com/search?searchon=contents&keywords=com_err.pc&mode=exactfilename&suite=noble&arch=any).

Re. #5, yeah, that will definitely make things easier. I'll likely get that finished and binaries released later today.

**Comment by pixincreate** [comment]
After I installed `comerr-dev`, it started to ask me to install `e2p` which I believe exist already. I went one step further and installed `libext2fs-dev` which resulted in compilation [failures](https://github.com/pixincreate/PixeneOS/actions/runs/10441861436/job/28913501273).

> On Linux, you should never need to set pkg-config paths.

But if I don't set the path, it throws [error](https://github.com/pixincreate/PixeneOS/actions/runs/10442234066/job/28914323785) stating it cannot `com_err`

**Comment by chenxiaolong** [comment]
```
 error[E0432]: unresolved import `crate::bindings::EXT2_ET_EXTERNAL_JOURNAL_NOSUPP`
  --> src/ext.rs:43:5
   |
43 |     EXT2_ET_EXTERNAL_JOURNAL_NOSUPP, EXT2_ET_FILE_EXISTS, EXT2_ET_FILE_NOT_FOUND, EXT2_ET_FILE_RO,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `EXT2_ET_EXTERNAL_JOURNAL_NOSUPP` in `bindings`
```

Ugh, Ubuntu 22.04's e2fsprogs is too outdated. And Github Action's `ubuntu-latest` is 22.04 instead of 24.04 for some reason (even though `ubuntu-24.04` is available).

Anyway, I'll be releasing the new binaries in a few minutes, so hopefully you won't have to deal with this again.

**Comment by pixincreate** [comment]
From what I know, `24.04` is still marked as beta, so I would have to explicitly mark it to use it.  

> Anyway, I'll be releasing the new binaries in a few minutes, so hopefully you won't have to deal with this again.

Waiting to update my workflow. It really means a lot! I really have no words to say at the moment.  

And yes, my entire project is completely dependent on your projects / repos.

**Comment by chenxiaolong** [comment]
Version 1.0.0 is now available: https://github.com/chenxiaolong/afsr/releases/tag/v1.0.0

**Comment by pixincreate** [comment]
On it. My workflow is being updated!

Thanks a lot!
